package org.basecamp.constant;

public enum StatusTypeEnum 
{
	SUBSCRIPTION_ORDER, 
	SUBSCRIPTION_CHANGE, 
	SUBSCRIPTION_CANCEL, 
	SUBSCRIPTION_NOTICE, 
	USER_ASSIGNMENT, 
	USER_UNASSIGNMENT,
	USER_UPDATED
	;

}
